//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienerLinienApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerHaltestellen
    {
        public int BenutzerHaltestelle_ID { get; set; }
        public int Benutzer_ID { get; set; }
        public int Haltestellen_ID { get; set; }
        public string Linie { get; set; }
        public string Richtung { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Haltestellen Haltestellen { get; set; }
    }
}
