//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienerLinienApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linien()
        {
            this.Steiges = new HashSet<Steige>();
        }
    
        public int Linien_ID { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<int> Reihenfolge { get; set; }
        public Nullable<int> Echtzeit { get; set; }
        public string Verkehrsmittel { get; set; }
        public string Stand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Steige> Steiges { get; set; }
    }
}
