//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienerLinienApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steige
    {
        public int Steig_Id { get; set; }
        public Nullable<int> FK_Linien_ID { get; set; }
        public Nullable<int> FK_Haltestellen_ID { get; set; }
        public string Richtung { get; set; }
        public string Reihenfolge { get; set; }
        public string RBL_Nummer { get; set; }
        public string Bereich { get; set; }
        public string Steig { get; set; }
        public Nullable<double> Steig_WGS84_LAT { get; set; }
        public Nullable<double> Steig_WGS84_LON { get; set; }
        public string Stand { get; set; }
    
        public virtual Haltestellen Haltestellen { get; set; }
        public virtual Linien Linien { get; set; }
    }
}
